refactor: Refactoring DataSource to DiscoveryService and updating tests
BBMRI-ERIC/negotiator pull request #199
Opened 2024-03-04 09:12 UTC by jungwire

## Negotiator pull request:

### Description:

Rename and simplify datasource table to discoveryservice

### Checklist:

_Make sure you tick all the boxes bellow if they are true or do not apply:_

- [x] I have performed a self review of my code
- [x] My code follows [Google Java Code style](https://google.github.io/styleguide/javaguide.html)
- [x] I have made my code as simple as possible
- [ ] I have added unit tests and the code coverage has not decreased
- [ ] I have updated the documentation in all relevant places

2024-03-07 18:39 UTC, RadovanTomik requested changes

2024-03-07 18:39 UTC, RadovanTomik commented on src/main/java/eu/bbmri_eric/negotiator/database/model/DiscoveryService.java
> +@Table(name = "discovery_service")
not sure if these are needed

2024-03-07 18:39 UTC, RadovanTomik commented on src/main/java/eu/bbmri_eric/negotiator/database/model/DiscoveryService.java
> +  public enum ApiType {
is this necessary?

2024-03-07 18:39 UTC, RadovanTomik commented on src/main/java/eu/bbmri_eric/negotiator/database/model/DiscoveryService.java
> +public class DiscoveryService extends AuditEntity {
add javadoc

2024-03-18 09:01 UTC, jungwire commented on src/main/java/eu/bbmri_eric/negotiator/database/model/DiscoveryService.java
> +@Table(name = "discovery_service")
removed @Table

2024-03-18 09:01 UTC, jungwire commented on src/main/java/eu/bbmri_eric/negotiator/database/model/DiscoveryService.java
> +  public enum ApiType {
removed ApiType

2024-03-18 09:01 UTC, jungwire commented on src/main/java/eu/bbmri_eric/negotiator/database/model/DiscoveryService.java
> +public class DiscoveryService extends AuditEntity {
added javadoc

2024-03-18 12:33 UTC, RadovanTomik requested changes

2024-03-18 12:33 UTC, RadovanTomik commented on src/main/java/eu/bbmri_eric/negotiator/api/controller/v3/DiscoverServiceController.java
>  }
Please change to /discovery-services, see https://restfulapi.net/resource-naming/

2024-03-18 12:33 UTC, RadovanTomik commented on src/main/java/eu/bbmri_eric/negotiator/configuration/security/OAuthSecurityConfig.java
>                      .hasAuthority("ADMIN")
see comment above

2024-03-18 12:33 UTC, RadovanTomik commented on src/main/java/eu/bbmri_eric/negotiator/dto/discoveryservice/DiscoveryServiceDTO.java
the DTO has an attribute description but the enditity doesn't have one, so please either add it to entity or remove it from DTO.

2024-03-25 15:12 UTC, RadovanTomik approved these changes

2024-03-25 15:59 UTC, merged