feat: Add functionality to disable posts in abandoned negotiations
BBMRI-ERIC/negotiator pull request #203
Opened 2024-03-05 13:55 UTC by jungwire

## Negotiator pull request:

### Description:

Adds functionality to disable posts in abandoned negotiations

### Checklist:

_Make sure you tick all the boxes bellow if they are true or do not apply:_

- [x] I have performed a self review of my code
- [x] My code follows [Google Java Code style](https://google.github.io/styleguide/javaguide.html)
- [x] I have made my code as simple as possible
- [x] I have added unit tests and the code coverage has not decreased
- [ ] I have updated the documentation in all relevant places

2024-03-05 19:44 UTC, RadovanTomik requested changes
please see comments and add a test in the NegotiationLifecycle tests where you change the state to abandoned and verify that postsEnabled is set to false

2024-03-05 19:44 UTC, RadovanTomik commented on src/main/java/eu/bbmri_eric/negotiator/configuration/state_machine/negotiation/DisablePostsAction.java
> +/** SpringStateMachine action for enabling posts in a Negotiation */
disabling

2024-03-05 19:44 UTC, RadovanTomik commented on src/main/java/eu/bbmri_eric/negotiator/configuration/state_machine/negotiation/NegotiationStateMachineConfig.java
> +        .action(disablePosts());
duplicate code, check few lines above

2024-03-19 09:17 UTC, jungwire commented on src/main/java/eu/bbmri_eric/negotiator/configuration/state_machine/negotiation/DisablePostsAction.java
> +/** SpringStateMachine action for enabling posts in a Negotiation */
corrected

2024-03-19 09:17 UTC, jungwire commented on src/main/java/eu/bbmri_eric/negotiator/configuration/state_machine/negotiation/NegotiationStateMachineConfig.java
> +        .action(disablePosts());
removed duplicated code

2024-03-21 09:13 UTC, RadovanTomik approved these changes

2024-03-21 13:32 UTC, merged