Add reminder emails functionality
BBMRI-ERIC/negotiator pull request #279
Opened 2024-04-10 07:36 UTC by jungwire

## Negotiator pull request:

### Description:

Introduces some changes to the notification email service by adding a functionality to send reminder emails for pending (negotiations that are under review) and stale (negotiations without ) to admins and representatives, respectively. The goal is to increase the responsiveness of biobanks/admins.

### Checklist:

_Make sure you tick all the boxes bellow if they are true or do not apply:_

- [ ] I have performed a self review of my code
- [x] My code follows [Google Java Code style](https://google.github.io/styleguide/javaguide.html)
- [ ] I have made my code as simple as possible
- [ ] I have added unit tests and the code coverage has not decreased
- [ ] I have updated the documentation in all relevant places

2024-04-15 12:02 UTC, RadovanTomik requested changes
why not just implement a nightly cron method that goes through all Negotiations create e.g. a week ago, looks at what resouces have had at least one status update and sends a notification to reps of those that didn't have an update?

2024-04-19 08:56 UTC, RadovanTomik requested changes
Please see commments

2024-04-19 08:56 UTC, RadovanTomik commented on src/main/java/eu/bbmri_eric/negotiator/service/UserNotificationServiceImpl.java
> +  private static Collection<NegotiationResourceState> activeNegotiationResourceStates =
why not do it the other way? nonActiveResource states are just Unavailable and Made available

2024-04-19 08:56 UTC, RadovanTomik commented on src/main/java/eu/bbmri_eric/negotiator/service/UserNotificationServiceImpl.java
> +  @Value("${reminder.trigger-duration-days:P14D}")
thinking about it now, change to 7 days

2024-04-19 08:56 UTC, RadovanTomik commented on src/main/java/eu/bbmri_eric/negotiator/service/UserNotificationServiceImpl.java
> +    Set<Person> representatives =
first you should just get resources involved in the Negotiation that did not have a new record in the last week/2 week. Then simply get their reps

2024-04-19 08:56 UTC, RadovanTomik commented on src/test/java/eu/bbmri_eric/negotiator/integration/service/UserNotificationServiceTest.java
> +  public void testSendReminderEmails() {
Not sure one test is enough for this. You should check multiple scenarios: for example set trigger duration to 0ms and then check if correct notifications were made

2024-04-19 08:56 UTC, RadovanTomik commented on src/main/java/eu/bbmri_eric/negotiator/database/model/NegotiationResourceLifecycleRecord.java
> +  @ManyToOne
not sure this is needed. Just go through the parent entity, if this is needed you need a migration script no?

2024-04-29 09:11 UTC, RadovanTomik approved these changes

2024-04-29 11:27 UTC, konradlang approved these changes

2024-04-29 12:34 UTC, merged