fix attachments memory consumption
BBMRI-ERIC/negotiator pull request #281
Opened 2024-04-11 14:47 UTC by svituz

## Negotiator pull request:

### Description:

This PR improves performance when getting attachments of big negotiations. It adds Blaze Persistence dependency since it gives the possibility, compared to JPA projection, to specify a subset of columns also for nested projections.
The authorization on objects (negotiation, attachments, and posts) is checked directly by querying the database instead of fetching unnecessary objects from the DB. 
This should improve memory usage.

### Checklist:

_Make sure you tick all the boxes below if they are true or do not apply:_

- [x] I have performed a self review of my code
- [x] My code follows [Google Java Code style](https://google.github.io/styleguide/javaguide.html)
- [x] I have made my code as simple as possible
- [x] I have added unit tests and the code coverage has not decreased
- [x] I have updated the documentation in all relevant places

2024-04-15 12:26 UTC, RadovanTomik requested changes
Please see comments, only minor things

2024-04-15 12:26 UTC, RadovanTomik commented on src/main/java/eu/bbmri_eric/negotiator/configuration/BlazePersitenceConfig.java
> +public class BlazePersitenceConfig {
typo

2024-04-15 12:26 UTC, RadovanTomik commented on src/main/java/eu/bbmri_eric/negotiator/database/model/Attachment.java
> +  @ManyToOne(fetch = FetchType.LAZY)
lazy is default state

2024-04-15 12:26 UTC, RadovanTomik commented on src/main/java/eu/bbmri_eric/negotiator/database/repository/NegotiationRepository.java
> +  boolean isRepresentativeOfAnyResource(String negotiationId, Long personId);
this method is not used

2024-04-15 12:26 UTC, RadovanTomik commented on src/main/java/eu/bbmri_eric/negotiator/database/repository/NegotiationRepository.java
> +  String negotiationWhereOrganization(String negotiationId, String organizationExternalId);
not used either

2024-04-15 12:26 UTC, RadovanTomik commented on pom.xml
> +<!--        </dependency>-->
please remove commented dep

2024-04-15 12:26 UTC, RadovanTomik commented on pom.xml
> +        </dependency>
are all these dependencies really needed? Isnt there a parent library containing all of them if yes?

2024-04-16 09:01 UTC, svituz commented on src/main/java/eu/bbmri_eric/negotiator/database/repository/NegotiationRepository.java
> +  String negotiationWhereOrganization(String negotiationId, String organizationExternalId);
removed

2024-04-16 09:01 UTC, svituz commented on src/main/java/eu/bbmri_eric/negotiator/database/repository/NegotiationRepository.java
> +  boolean isRepresentativeOfAnyResource(String negotiationId, Long personId);
removed

2024-04-16 09:03 UTC, svituz commented on src/main/java/eu/bbmri_eric/negotiator/database/model/Attachment.java
> +  @ManyToOne(fetch = FetchType.LAZY)
removed

2024-04-16 12:16 UTC, RadovanTomik requested changes
just some small issues

2024-04-16 12:16 UTC, RadovanTomik commented on src/main/java/eu/bbmri_eric/negotiator/service/DBAttachmentService.java
> +  @Autowired private PersonRepository personRepository;
please remove the autowired annotations and use a classic constructor

2024-04-16 12:16 UTC, RadovanTomik commented on src/main/java/eu/bbmri_eric/negotiator/service/DBAttachmentService.java
> +    // checks whether the user is representative of the organization
please remove comments and rather extract the logic into a separate method with an appropriate name

2024-04-16 12:16 UTC, RadovanTomik commented on src/main/java/eu/bbmri_eric/negotiator/service/DBAttachmentService.java
>        // 3. addressed to the organization represented by the authenticated user
same here

2024-04-17 07:57 UTC, RadovanTomik approved these changes

2024-04-17 07:57 UTC, merged