docs: Update NOTIFICATIONS.md with detailed configuration and template information
BBMRI-ERIC/negotiator pull request #441
Opened 2024-09-12 10:56 UTC by jungwire

## Negotiator pull request:

### Description:

Updated and added additional information for the email template used for the notifications

### Checklist:

_Make sure you tick all the boxes below if they are true or do not apply before you ask for review_

- [x] I have performed a self-review of my code
- [x] I have made my code as simple as possible
- [x] I have added relevant tests for my changes and the code coverage has not dropped substantially
- [x] I have removed all commented code
- [x] I have updated the documentation in all relevant places (Javadoc, Swagger, MDs...)
- [x] I have described the PR and added a meaningful title in the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format

2024-09-14 15:57 UTC, RadovanTomik requested changes
please see comments, also is there a reason why it is not part of #442 ?

2024-09-14 15:57 UTC, RadovanTomik commented on docs/NOTIFICATIONS.md
> +spring.thymeleaf.cache=false
maybe set this property for application-dev.yaml? so devs can take advantage of it?

2024-09-14 15:57 UTC, RadovanTomik commented on docs/NOTIFICATIONS.md
> + - To edit the template, open the `email-notification.html` file.
maybe also provide instructions on how to upload a custom file for docker containers?

2024-09-18 11:39 UTC, jungwire commented
merged this into https://github.com/BBMRI-ERIC/negotiator/tree/feat/add_variable_email_template branche and added requested changes

2024-09-18 11:39 UTC, closed without merging