feat: add variables for email template
BBMRI-ERIC/negotiator pull request #442
Opened 2024-09-12 15:57 UTC by tmilost

## Negotiator pull request:

### Description:

User can configure in global variable, what is displayed in email template

### Checklist:

_Make sure you tick all the boxes below if they are true or do not apply before you ask for review_

- [ʕノ•ᴥ•ʔノ ︵ ┻━┻] I have performed a self-review of my code
- [ʕノ•ᴥ•ʔノ ︵ ┻━┻] I have made my code as simple as possible
- [ʕノ•ᴥ•ʔノ ︵ ┻━┻] have added relevant tests for my changes and the code coverage has not dropped substantially
- [ʕノ•ᴥ•ʔノ ︵ ┻━┻] I have removed all commented code
- [ʕノ•ᴥ•ʔノ ︵ ┻━┻] I have updated the documentation in all relevant places (Javadoc, Swagger, MDs...)
- [ʕノ•ᴥ•ʔノ ︵ ┻━┻] I have described the PR and added a meaningful title in the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format

2024-09-12 15:58 UTC, tmilost commented
@jungwire Feel free to change whatever you think is necessary

2024-09-14 15:54 UTC, RadovanTomik requested changes
were the changes made discussed with the person who requested these changes? There is no issue linked. Maybe add some tests or enable uploading a fully customized template file.

2024-09-14 15:54 UTC, RadovanTomik commented on src/main/resources/application.yaml
> +  emailHelpdeskHref: ""
please set it to BBMRI-ERIC by default and remove it from other property files

2024-09-18 11:35 UTC, jungwire commented
merged the documentation branch in to this one

2024-09-19 08:26 UTC, RadovanTomik requested changes
please just set the email config variables in application.yml with defuault values

2024-09-24 12:56 UTC, merged